#!/bin/bash
a=(a b c d)
#echo ${a[1]}
a[3]=e
a[5]=g
#echo ${a[@]}
str="# Query_time: 0.034771  Lock_time: 0.000076 Rows_sent: 1000  Rows_examined: 16000"
b=($str)
#cho "3*4.333"|bc  | awk -F.  '{print $1}'
num=`echo "${b[2]} * 10000" | bc | awk -F. '{print $1}' `
echo ${b[2]}
echo "$num"
if [ -z ${b[100]} ];then
  echo 123123123
fi
#a[]="abcd"
echo ${#a[@]}

big=(3 1 4 5 2 6 23 4)
echo ${big[@]} | sort -t 
