#!/bin/bash

file="/home/dinglin/下载/slowquery/temp_data"
tmp="/home/dinglin/下载/slowquery/temp_simple"

echo "" > "$tmp"

sql=""

db=""
time=""
query_time=""

#cat "$file" | grep "Query_time" | sort -r -k 3 | head -n "$max_num" > "$tmp"

while read line
do
    #data
    start=`echo "$line" | awk '{print toupper($1)}'`
    second=`echo "$line" | awk '{print toupper($2)}'`
    a_line=($line)

    #build sql
    if [ "$start" = "INSERT" ] || [ "$start" = "DELETE" ] || [ "$start" = "UPDATE" ] || [ "$start" = "SELECT" ];then
       sql="$line"
    elif [ "$start" = "#" ] && [ "$second" = "USER@HOST:" ];then  #user host
        if [ -z "$sql" ];then
            continue
        fi
        start=`echo "$sql " | awk '{print toupper($1)}'`
        table=""
        open="false"
        table_start=""
        table_end=""
        if [ "$start" = "SELECT" ];then
            table_start="FROM"
            table_end="WHERE"
        elif [ "$start" = "DELETE" ];then
            table_start="FROM"
            table_end="WHERE"        
        elif [ "$start" = "UPDATE" ];then
            table_start="UPDATE"
            table_end="SET"
        elif [ "$start" = "INSERT" ];then
            table_start="INTO"
            table_end="END"
        fi
        for i in $sql;do
            i=`echo "$i " | awk '{print toupper($1)}'`
            if [ "$i" = "$table_start" ];then
                open="true"
            elif [ "$i" = "$table_end" ];then 
                open="false"
                break
            elif [ "$open" = "true" ];then  
                table+="$i"
                if [ "$table_end" = "END" ];then
                    break
                fi
            fi
        done  
        db=`echo "$db" | sed 's/;//'`
        table=`echo "$table" | sed 's/(.*//'`
        table=$(echo "$table" | sed 's/`//g')
        if [ -n "$table" ];then
            table=`echo "$table " | awk '{print tolower($1)}'`
            echo "# $db $table $query_time $time $sql" >> "$tmp"
        fi
    elif [ "$start" = "#" ] && [ "$second" = "TIME:" ];then  #time
        time=${a_line[3]}
    elif [ "$start" = "#" ] && [ "$second" = "QUERY_TIME:" ];then  #query time
        query_time=${a_line[2]}
    elif [ "$start" = "USE" ];then #db
        db=${a_line[1]}
    elif [ "$start" != "#" ] && [ "$start" != "USE" ] && [ "$start" != "SET" ];then
        sql+=" "        
        sql+="$line"
    fi
done < "$file"
